import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:meditag_reader/protocol.dart';
import 'package:meditag_reader/tag_verifier.dart';

void main() {
  test('decodes the fixed 15-byte Tier 1 layout', () {
    final payload = Tier1Payload.decode(Uint8List.fromList([
      1, 8, // v1, O-
      0, 17, // penicillin and latex
      0, 1, // diabetes
      0x98, 0x76, 0x54, 0x32, 0x10, // 9876543210 packed BCD
      0, 0, 3, 233, // tag ID 1001
    ]));
    expect(payload.bloodTypeName, 'O-');
    expect(payload.allergies, ['Penicillin', 'Latex']);
    expect(payload.conditions, ['Diabetes']);
    expect(payload.emergencyPhone, '9876543210');
    expect(payload.tagId, 1001);
  });

  test('verifies a P-256 signature issued by the Python backend', () async {
    // Generated by backend/app/main.py; test vector has no real patient data.
    const publicKey = 'BGr2PeN/0ffDZ4VA644N3hp3XTLrXRasbNjlLiq1UZmqTmq0Qc6TibCquRVfuJtVYrHeVsjNzJECGaPCtd3RpuI=';
    const signedPayload = 'AQgAEQABmHZUMhAAAAPp+LcdMylJAL33xGBiQvqS6vaBsztZeKce456cGctp831v5+KuSt04tVNzrKeg7ooLFKmiIvQ/Kw0UteyOFWZobw==';
    final verifier = TagVerifier(TagVerifier.publicKeyFromUncompressed(Uint8List.fromList(base64Decode(publicKey))));
    final result = await verifier.verify(Uint8List.fromList(base64Decode(signedPayload)));
    expect(result.isVerified, isTrue);
    expect(result.payload!.tagId, 1001);
  });
}
